Update Jekyll gem and other Ruby gems
After updating the Ruby version, the following problem occurred:

>  Liquid Exception: undefined method `tainted?'
> for "/article/2008/10/21/pierwsze-spotkanie.html":String
> in srug.github.io/_layouts/post.html
>                    ------------------------------------------------
>      Jekyll 4.2.0   Please append `--trace` to the `serve` command
>                     for any additional information or backtrace.
>                    ------------------------------------------------
> /gems/ruby-3.2.2@srug.pl/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in
> `taint_check': undefined method `tainted?'
> for "/article/2008/10/21/pierwsze-spotkanie.html":String
> (NoMethodError)
>
>      return unless obj.tainted?
>                       ^^^^^^^^^

There is an issue with Liquid on newer versions of Ruby. [1]
We don't want to use an old version of Ruby, which is probably obvious.
The bundler found a satisfactory solution.
It selected the appropriate versions of the gems,
including the Liquid library version 4.0.4.

[1]: jekyll/jekyll#9233
[2]: jekyll/jekyll#9233 (comment)
[3]: https://rubygems.org/gems/liquid/versions/4.0.4
[4]: Shopify/liquid#1668